repos:
    - repo: https://github.com/humitos/mirrors-autoflake
      rev: v1.3
      hooks:
          - id: autoflake
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black
            exclude: setup.py
    - repo: https://github.com/PyCQA/flake8
      rev: 3.7.9
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
            additional_dependencies: ["isort[pyproject]"]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.761
      hooks:
          - id: mypy
    - repo: https://github.com/mverteuil/precommit-dephell
      rev: master
      hooks:
        - id: dephell
        - id: pyproject-toml-to-requirements-txt
