repos:
    - repo: https://github.com/humitos/mirrors-autoflake
      rev: v1.3
      hooks:
          - id: autoflake
    - repo: https://github.com/psf/black
      rev: 21.7b0
      hooks:
          - id: black
            exclude: setup.py|.*_pb2.py
    - repo: https://github.com/PyCQA/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.2
      hooks:
          - id: isort
            exclude: .*_pb2.py
            additional_dependencies: ["isort[pyproject]"]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
          - id: mypy
            pass_filenames: false
            additional_dependencies:
              - types-protobuf
              - types-six
              - types-filelock
              - types-setuptools
              - types-toml
    # - repo: https://github.com/mverteuil/precommit-dephell
    #   rev: d62e4fd01b6616a673d2305d6eb0f2bd45556996
    #   hooks:
    #     - id: dephell
    - repo: local
      hooks:
          - id: export-requirements
            name: Export requeriments.txt
            language: system
            pass_filenames: false
            entry: poetry export --without-hashes --dev -o requirements.txt
            files: ^(pyproject.toml|poetry.lock)$
