name: amanda
dependencies:
    - python=3.7
    - pip
    - tensorflow=1.13.1=mkl*
    - pytorch::pytorch=1.4.0
    - pytorch::torchvision=0.5.0
    - cudatoolkit=10.1
    - pip:
        - poetry==1.0.0
