name: mmx
dependencies:
    - python=3.7
    - pip
    - tensorflow=1.15.0=mkl*
    - pytorch::pytorch=1.3.1
    - pytorch::torchvision=0.4.2
    - cudatoolkit=10.1
    - pip:
        - poetry==1.0.0b8 --index-url https://pypi.org/simple
