# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='amanda',
    version='0.1.0',
    description='graph instrumentation',
    python_requires='<4,>=3.6.1',
    project_urls={
        "homepage": "https://github.com/uchuhimo/amanda",
        "repository": "https://github.com/uchuhimo/amanda"
    },
    author='uchuhimo',
    author_email='uchuhimo@outlook.com',
    license='Apache-2.0',
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English', 'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8'
    ],
    entry_points={
        "console_scripts": [
            "amanda = amanda.cli.main:cli",
            "amanda-download = amanda.cli.download:cli",
            "amanda-run = amanda.cli.run:cli"
        ]
    },
    packages=[
        'amanda', 'amanda.cli', 'amanda.conversion', 'amanda.io',
        'amanda.tests', 'amanda.tests.tensorflow',
        'amanda.tests.tensorflow.models',
        'amanda.tests.tensorflow.models.mobilenet', 'amanda.tools',
        'amanda.tools.byteps', 'amanda.tools.byteps.tensorflow',
        'amanda.tools.debugging', 'amanda.tools.path'
    ],
    package_dir={"": "src"},
    package_data={
        "amanda.io": ["*.proto", "*.pyi"],
        "amanda.tests": ["*.pbtxt"],
        "amanda.tools.debugging": ["*.json", "*.yaml"],
        "amanda.tools.path": ["*.yaml"]
    },
    install_requires=[
        'click', 'contextvars; python_version < "3.7"',
        'dataclasses; python_version < "3.7"', 'h5py', 'immutables', 'loguru',
        'more-itertools', 'protobuf', 'ruamel.yaml',
        'typing; python_version < "3.7"', 'typing-extensions'
    ],
    extras_require={
        "dev": [
            "black", "bump2version", "coverage[toml]", "dephell[full]",
            "filelock", "fissix", "flake8", "ipython", "isort[pyproject]",
            "jsondiff", "mmdnn", "mypy", "mypy-protobuf", "numpy", "onnx",
            "onnxruntime", "pip>=19.3", "pre-commit", "pytest", "pytest-xdist",
            "scipy", "sphinx", "tensorflow==1.15.3", "torch==1.6.0",
            "torchvision==0.7.0", "tox", "twine", "watchdog", "wget", "wheel"
        ]
    },
)
