# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from amanda.io.value_pb2 import (
    DataTypeValue as amanda___io___value_pb2___DataTypeValue,
    SerializedValue as amanda___io___value_pb2___SerializedValue,
    Struct as amanda___io___value_pb2___Struct,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class PortDef(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    @property
    def type(self) -> amanda___io___value_pb2___DataTypeValue: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        type : typing___Optional[amanda___io___value_pb2___DataTypeValue] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"type",b"type"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"type",b"type"]) -> None: ...
type___PortDef = PortDef

class EdgeDef(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def src(self) -> amanda___io___value_pb2___SerializedValue: ...

    @property
    def dst(self) -> amanda___io___value_pb2___SerializedValue: ...

    @property
    def attrs(self) -> amanda___io___value_pb2___Struct: ...

    def __init__(self,
        *,
        src : typing___Optional[amanda___io___value_pb2___SerializedValue] = None,
        dst : typing___Optional[amanda___io___value_pb2___SerializedValue] = None,
        attrs : typing___Optional[amanda___io___value_pb2___Struct] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"attrs",b"attrs",u"dst",b"dst",u"src",b"src"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"attrs",b"attrs",u"dst",b"dst",u"src",b"src"]) -> None: ...
type___EdgeDef = EdgeDef

class NodeDef(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    NodeKindValue = typing___NewType('NodeKindValue', builtin___int)
    type___NodeKindValue = NodeKindValue
    NodeKind: _NodeKind
    class _NodeKind(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[NodeDef.NodeKindValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        OP = typing___cast(NodeDef.NodeKindValue, 0)
        GRAPH = typing___cast(NodeDef.NodeKindValue, 1)
        SUBGRAPH = typing___cast(NodeDef.NodeKindValue, 2)
    OP = typing___cast(NodeDef.NodeKindValue, 0)
    GRAPH = typing___cast(NodeDef.NodeKindValue, 1)
    SUBGRAPH = typing___cast(NodeDef.NodeKindValue, 2)
    type___NodeKind = NodeKind

    node_kind: type___NodeDef.NodeKindValue = ...
    name: typing___Text = ...
    type: typing___Text = ...
    namespace: typing___Text = ...

    @property
    def input_ports(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PortDef]: ...

    @property
    def output_ports(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PortDef]: ...

    @property
    def ops(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___NodeDef]: ...

    @property
    def edges(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___EdgeDef]: ...

    @property
    def attrs(self) -> amanda___io___value_pb2___Struct: ...

    def __init__(self,
        *,
        node_kind : typing___Optional[type___NodeDef.NodeKindValue] = None,
        name : typing___Optional[typing___Text] = None,
        type : typing___Optional[typing___Text] = None,
        namespace : typing___Optional[typing___Text] = None,
        input_ports : typing___Optional[typing___Iterable[type___PortDef]] = None,
        output_ports : typing___Optional[typing___Iterable[type___PortDef]] = None,
        ops : typing___Optional[typing___Iterable[type___NodeDef]] = None,
        edges : typing___Optional[typing___Iterable[type___EdgeDef]] = None,
        attrs : typing___Optional[amanda___io___value_pb2___Struct] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"attrs",b"attrs"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"attrs",b"attrs",u"edges",b"edges",u"input_ports",b"input_ports",u"name",b"name",u"namespace",b"namespace",u"node_kind",b"node_kind",u"ops",b"ops",u"output_ports",b"output_ports",u"type",b"type"]) -> None: ...
type___NodeDef = NodeDef
